# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=15, verbose_name='学号')),
                ('chinese', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='语文')),
                ('math', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='数学')),
                ('english', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='英语')),
                ('physical', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='物理')),
                ('chemistry', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='化学')),
                ('biological', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='生物')),
                ('political', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='政治')),
                ('history', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='历史')),
                ('geography', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='地理')),
                ('sports', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='体育')),
                ('art', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='美术')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
            ],
        ),
    ]
