# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=15, verbose_name='学号')),
                ('img', models.ImageField(upload_to='picture', verbose_name='学生作品')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isActive', models.BooleanField(default=True, verbose_name='状态')),
            ],
        ),
    ]
