# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-23 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_artwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentscore',
            options={'verbose_name': '学生成绩', 'verbose_name_plural': '学生成绩'},
        ),
        migrations.AlterModelTable(
            name='studentscore',
            table='score',
        ),
    ]
