# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-07 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='stu_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='school_id',
            new_name='school',
        ),
    ]
