# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-09 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191107_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='teacherid',
        ),
    ]
