# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-18 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191109_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='login_time',
            field=models.DateTimeField(null=True, verbose_name='登录时间'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='login_time',
            field=models.DateTimeField(null=True, verbose_name='登录时间'),
        ),
    ]
