# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191118_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='电话'),
        ),
    ]
